pipeline {
    agent any
    stages {
        stage('Container Build') {
            steps {
                sh 'docker container run -d --name mysql --network lmsnetwork -e MYSQL_ROOT_PASSWORD=Qwerty@123 -p 3307:3306 mysql:latest'
            }
        }   
   stages {
        stage('Docker Build') {
            steps {
                sh 'cd LMS-BE && docker build -t backend .'
            }
        }   
        stage('container remove') {
            steps {
                sh 'docker container rm -f be'
            }
        }
        stage('Docker container') {
            steps {
                sh 'docker container run -dt --name be -p 9090:8080 backend'
            }
        }
    }
}
}  
    
